### ISSUE TITLE
Sheng Shiong py script code does not work

### ISSUE THREAD

**Issue by RealDyllon** [19hours/19hours.github.io#1]
Awesome work with the supermarket wars post and code!

However, the Sheng Shiong code doesn't seem to work for me. There seems to be an issue with the post request to allforyou.sg, which returns an error. Same result when tested in postman

I noticed that allforyou.sg sends a many headers in the post request. Could a missing header be preventing us from getting a response?

**Comment by 19hours** [comment]
What's the error? I'm getting the correct response from sheng siong

`{'result': 'No more timeslots.', 'response': 'Failed'}`

**Comment by RealDyllon** [comment]
@19hours Thanks for the quick response. 

Yup, it was my fault. I accidentally used GET instead of POST, when I ported the code to NodeJS.
